### PR TITLE
Transient protection, maps, sparsearray, import fixes

### PR DESCRIPTION
**Pull request by dallasgutauckis**

### CODE REVIEW

**Comment by dallasgutauckis** [comment]
@mcharmas Can you make sure there wasn't a regression on List<T> where T doesn't implement Parcelable? I don't know that the plugin previously protected this from using read/writeValue but it seems to do that with this review. If it wasn't a regression in this build you should still merge this, but we should write something for that use case.

Here's something to test with
```
    static class TestParcelable {

        SparseArray<NonParcelableType> sparseBools;

        List<NonParcelableType> nonParcelableTypeList = new ArrayList<NonParcelableType>();
        List<ParcelableType> parcelableTypeList = new ArrayList<ParcelableType>();

        public transient boolean testTransient;

        Map<NonParcelableType, Boolean> myMap;
    }
```

**Comment by dallasgutauckis** [comment]
@mcharmas Bump

**Comment by mcharmas** [comment]
I've merged your code locally, fixed some issues and completely rewritten your map serialization for more generic solution. I'll try to release this on Tuesday and let you know to test it if you can.

**Comment by dallasgutauckis** [comment]
Sounds good. Thanks :-)

**Pull request merged**
