### PR TITLE
Map SparseArray & transient modifier support

### PR DESCRIPTION
**Pull request by dallasgutauckis**
New support for:
 - `SparseArray`
 - `Map` (always assumes `HashMap`)
 - `transient` modifier

### CODE REVIEW

**Comment by seviu** [comment]
Despite the comments in the pull request, maybe this pull request should be merged. Support for Lists and Maps plus transient modifier support is pretty much needed for this plugin to be complete.

**Comment by passsy** [comment]
+1 for `transient` support

**Comment by mcharmas** [comment]
@dallasgutauckis could you please rebase this against current master? I'll check it out, merge it and release to plugins repo.

**Comment by dallasgutauckis** [comment]
A lot of things changed underneath this review and required a bigger change — but I also had other local optimizations unsubmitted so I'm going to make a new PR with changes.

**Pull request closed without merging**
